# Generated by Django 4.2 on 2023-04-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_camera_motoinfo_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
