# Generated by Django 4.2 on 2023-04-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_objectresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectresponse',
            name='image_url',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objectresponse',
            name='licence_plate',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objectresponse',
            name='locate',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
